kind: Template
apiVersion: v1
metadata:
  name: BuildConfig to build restore image for OpenShift
  annotations:
    description: "Template creates buildconfig and imagestream to create a image for restoring data from backup"
    tags: "restore"
objects:
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: openshift-restore-image
      annotations:
        description: Build image to perform restore. Source from Github
    spec:
      source:
        type: Git
        git:
          uri: "${SOURCE_REPOSITORY_URL}" 
          ref: "${SOURCE_REPOSITORY_REF}"
        contextDir: "${CONTEXT_DIR_BACKUP}"
      output:
        to:
          kind: "ImageStreamTag"
          name: "openshift-restore-image:latest"
      strategy:
        type: Docker
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: openshift-restore-image
    spec:
      tags:
        - name: latest
parameters:
  - name: SOURCE_REPOSITORY_URL 
    displayName: Source Repository URL 
    description: The URL of the repository for openshift-backup project 
    value: https://github.com/vadimzharov/openshift-backup.git
    required: true 
  - name: SOURCE_REPOSITORY_REF
    description: Github branch
    value: centos-base
    required: true 
  - name: CONTEXT_DIR_BACKUP
    description: Directory with Dockerfile to build metadata-backup image
    value: restore
    required: true

