kind: Template
apiVersion: v1
metadata:
  name: backup-openshift-all-files-build-image
  annotations:
    description: "Template creates image to perform backup of all PVCs in one OpenShift project (better to use project named openshift)"
    tags: "backup"
objects:
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: openshift-backup-all-files-image
      annotations:
        description: Build image to perform backup of all PVCs in one OpenShift project
    spec:
      source:
        type: Git
        git:
          uri: "${SOURCE_REPOSITORY_URL}" 
          ref: "${SOURCE_REPOSITORY_REF}"
        contextDir: "${CONTEXT_DIR_BACKUP}"
      output:
        to:
          kind: "ImageStreamTag"
          name: "openshift-backup-all-files:latest"
      strategy:
        type: Docker
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: openshift-backup-all-files
    spec:
      tags:
        - name: latest
parameters:
  - name: SOURCE_REPOSITORY_URL
    displayName: Source Repository URL 
    description: The URL of the repository for openshift-backup project 
    value: https://github.com/vadimzharov/openshift-backup.git
    required: true 
  - name: SOURCE_REPOSITORY_REF
    description: Github branch
    value: master
    required: true 
  - name: CONTEXT_DIR_BACKUP
    description: Directory with Dockerfile to build metadata-backup image
    value: backup-all-pvc
    required: true
  - name: CONTEXT_DIR_RESTORE
    description: Directory with Dockerfile to build metadata-restore image
    value: all-files/restore
    required: true
labels:
  openshift-backup: all-files
