kind: Template
apiVersion: v1
metadata:
  name: restore-project-files
  annotations:
    description: "Template creates job to restore files in one PVC. If PVC not exists - restore will be canceled. "
    tags: "restore"
objects:
  - kind: Job
    apiVersion: batch/v1
    metadata:
      name: ${JOB_NAME}
      annotations:
        description: Restore project files
    spec:
      parallelism: 1
      completions: 1
      template:
        metadata:
          name: project-files-restore
        spec:
          containers:
          - name: ${JOB_NAME}
            image: docker-registry.default.svc:5000/openshift/openshift-restore-image:latest
            env:
              - name: BACKUP_TYPE
                value: ${BACKUP_TYPE}
              - name: RESTIC_PASSWORD
                value: ${RESTIC_PASSWORD}
              - name: PROJECT_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace  
              - name: RESTIC_TAG
                value: ${CUSTOM_TAG}
              - name: RESTIC_DESTINATION
                value: ${RESTIC_DESTINATION}
              - name: AWS_ACCESS_KEY_ID
                value: ${AWS_ACCESS_KEY}
              - name: AWS_SECRET_ACCESS_KEY
                value: ${AWS_SECRET_ACCESS_KEY}
              - name: RESTIC_S3_HOST
                value: ${RESTIC_HOST}
              - name: RESTIC_SNAPSHOT
                value: ${RESTIC_SNAPSHOT}
            volumeMounts:
              - mountPath: /data
                name: backup-target
          restartPolicy: Never
          volumes:
            - name: backup-target
              persistentVolumeClaim:
                claimName: ${CUSTOM_TAG}
parameters:
  - name: BACKUP_TYPE
    value: files
  - name: CUSTOM_TAG
    displayName: Name of PVC
    description: Enter name of PVC which you want to restore. If PVC not exists - restore will be canceled. 
    required: true
  - name: RESTIC_PASSWORD 
    displayName: Password for restic repository
    description: Password for your current restic repository. No password - no restore. 
    value: 123qweASD
    required: true 
  - name: RESTIC_DESTINATION
    description: Access protocol to access to your restic repository. Currently only S3 is supported
    value: s3
    required: true
  - name: RESTIC_HOST
    description: Server where your data placed
    value: jump02.home.msk
    required: true
  - name: AWS_ACCESS_KEY
    description: Access key for your S3 server
    value: 123qweASD
    required: true
  - name: AWS_SECRET_ACCESS_KEY
    description: Secret access key for your S3 server
    value: 123qweASD
    required: true
  - name: RESTIC_SNAPSHOT
    description: Snapshot ID. Default parameter is latest (restore from last backup)
    value: latest
    required: true
  - name: JOB_NAME
    description: Job's name
    value: project-files-restore
    required: true
labels:
  openshift-restore: files