kind: Template
apiVersion: v1
metadata:
  name: prepare-for-backup
  annotations:
    description: "Template creates required OpenShift objects (templates and service accounts)
      to perform all kind of restore your data (project metadata, files, databases)
      In some cases this job has to be run as root (to set correct ownership for restored files.
      The template will create service account restore-sa to do it, but you have to setup correct SCC (anyuid)"
    tags: "backup"
objects:
  - kind: ServiceAccount
    apiVersion: v1
    metadata:
      name: restore-sa
  - kind: RoleBinding
    apiVersion: v1
    metadata:
      name: api_CREATE_for_restore
    roleRef:
      name: edit
    subjects:
    - kind: ServiceAccount
      name: restore-sa
  - kind: Secret
    apiVersion: v1
    metadata:
      name: backup-credentials
    stringData:
      RESTIC_PASSWORD: ${GLOBAL_RESTIC_PASSWORD}
      RESTIC_DESTINATION: ${GLOBAL_RESTIC_DESTINATION}
      AWS_ACCESS_KEY_ID: ${GLOBAL_AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${GLOBAL_AWS_SECRET_ACCESS_KEY}
      RESTIC_HOST: ${GLOBAL_RESTIC_HOST}
      RESTIC_S3_PORT: ${GLOBAL_RESTIC_S3_PORT}
      RESTIC_KEEP: ${GLOBAL_RESTIC_KEEP}
      CHANGE_NAMESPACE: ${GLOBAL_CHANGE_NAMESPACE}
      PROJECT_NAME: ${GLOBAL_PROJECT_NAME}
  - kind: Template
    apiVersion: v1
    metadata:
      name: restore-project-metadata
      annotations:
        description: "Template creates job to run project metadata retore from your backup. 
          It requires service account to work correctly (restore-sa)."
        tags: "restore"
    objects:
    - kind: Job
      apiVersion: batch/v1
      metadata:
        name: ${JOB_NAME}
        annotations:
          description: Restore project metadata
      spec:
        parallelism: 1
        completions: 1
        template:
          metadata:
            name: project-metadata-restore
          spec:
            containers:
            - name: project-metadata-restore
              image: docker.io/vadimzharov/openshift-restore-image:latest
              env:
                - name: BACKUP_TYPE
                  value: metadata
                - name: RESTIC_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: backup-credentials
                      key: RESTIC_PASSWORD
                - name: NEW_PROJECT_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace  
                - name: RESTIC_TAG
                  value: metadata
                - name: RESTIC_DESTINATION
                  valueFrom:
                    secretKeyRef:
                      name: backup-credentials
                      key: RESTIC_DESTINATION
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: backup-credentials
                      key: AWS_ACCESS_KEY_ID
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: backup-credentials
                      key: AWS_SECRET_ACCESS_KEY
                - name: RESTIC_HOST
                  valueFrom:
                    secretKeyRef:
                      name: backup-credentials
                      key: RESTIC_HOST
                - name: RESTIC_S3_PORT
                  valueFrom:
                    secretKeyRef:
                      name: backup-credentials
                      key: RESTIC_S3_PORT
                - name: CHANGE_NAMESPACE
                  valueFrom:
                    secretKeyRef:
                      name: backup-credentials
                      key: CHANGE_NAMESPACE
                - name: PROJECT_NAME
                  valueFrom:
                    secretKeyRef:
                      name: backup-credentials
                      key: PROJECT_NAME
                - name: API_TO_RESTORE
                  value: ${API_TO_RESTORE}                      
            serviceAccount: restore-sa
            serviceAccountName: restore-sa
            restartPolicy: Never
    parameters:
    - name: JOB_NAME
      displayName: Name of the job.
      description: Name of the job. It has to be unique in the project (just add a number in the name)
      value: project-metadata-restore
      required: true
    - name: API_TO_RESTORE 
      displayName: Which metadata do you want to restore?
      description: Enter (o)api endpoint which you want to restore. Keep empty to restore all metadata for all endpoints.
      value: ""
  - kind: Template
    apiVersion: v1
    metadata:
      name: restore-project-files
      annotations:
        description: "Template creates job to restore all files for one PVC. You need to enter PVC name."
        tags: "restore"
    objects:
      - kind: Job
        apiVersion: batch/v1
        metadata:
          name: ${JOB_NAME}
          annotations:
            description: Restore project files for one PVC
        spec:
          parallelism: 1
          completions: 1
          template:
            metadata:
              name: project-files-restore
            spec:
              containers:
              - name: ${JOB_NAME}
                image: docker.io/vadimzharov/openshift-restore-image:latest
                env:
                  - name: BACKUP_TYPE
                    value: files
                  - name: RESTIC_PASSWORD
                    valueFrom:
                      secretKeyRef:
                        name: backup-credentials
                        key: RESTIC_PASSWORD
                  - name: NEW_PROJECT_NAME
                    valueFrom:
                      fieldRef:
                        fieldPath: metadata.namespace  
                  - name: RESTIC_TAG
                    value: ${CUSTOM_TAG}
                  - name: RESTIC_DESTINATION
                    valueFrom:
                      secretKeyRef:
                        name: backup-credentials
                        key: RESTIC_DESTINATION
                  - name: AWS_ACCESS_KEY_ID
                    valueFrom:
                      secretKeyRef:
                        name: backup-credentials
                        key: AWS_ACCESS_KEY_ID
                  - name: AWS_SECRET_ACCESS_KEY
                    valueFrom:
                      secretKeyRef:
                        name: backup-credentials
                        key: AWS_SECRET_ACCESS_KEY
                  - name: RESTIC_HOST
                    valueFrom:
                      secretKeyRef:
                        name: backup-credentials
                        key: RESTIC_HOST
                  - name: RESTIC_S3_PORT
                    valueFrom:
                      secretKeyRef:
                        name: backup-credentials
                        key: RESTIC_S3_PORT
                  - name: RESTIC_SNAPSHOT
                    description: Restic snapshot id
                    value: ${RESTIC_SNAPSHOT}
                    required: true
                  - name: PROJECT_NAME
                    valueFrom:
                      secretKeyRef:
                        name: backup-credentials
                        key: PROJECT_NAME            
                volumeMounts:
                  - mountPath: /data
                    name: backup-target
              restartPolicy: Never
              volumes:
                - name: backup-target
                  persistentVolumeClaim:
                    claimName: ${CUSTOM_TAG}
              serviceAccount: restore-sa
              serviceAccountName: restore-sa                    
    parameters:
      - name: JOB_NAME
        displayName: Name of the job.
        description: Name of the job. It has to be unique in the project (just add a number in the name)
        value: project-files-restore
        required: true
      - name: CUSTOM_TAG
        displayName: Enter name of existing PVC
        description: Type persistent volume claim name (in your project). It should be existing pvc.
        value: postgresql
        required: true 
  - kind: Template
    apiVersion: v1
    metadata:
      name: restore-project-databases
      annotations:
        description: "Template creates job to run database (MYSQL and PGSQL) restore. 
        You need to know service name where is your database works."
        tags: "restore"
    objects:
      - kind: Job
        apiVersion: batch/v1
        metadata:
          name: ${JOB_NAME}
          annotations:
            description: Restore project database
        spec:
          parallelism: 1
          completions: 1
          template:
            metadata:
              name: project-database-restore
            spec:
              containers:
              - name: ${JOB_NAME}
                image: docker.io/vadimzharov/openshift-restore-image:latest
                env:
                  - name: BACKUP_TYPE
                    value: databases
                  - name: RESTIC_PASSWORD
                    valueFrom:
                      secretKeyRef:
                        name: backup-credentials
                        key: RESTIC_PASSWORD
                  - name: NEW_PROJECT_NAME
                    valueFrom:
                      fieldRef:
                        fieldPath: metadata.namespace  
                  - name: RESTIC_TAG
                    value: ${DATABASE_SVC}
                  - name: RESTIC_DESTINATION
                    valueFrom:
                      secretKeyRef:
                        name: backup-credentials
                        key: RESTIC_DESTINATION
                  - name: AWS_ACCESS_KEY_ID
                    valueFrom:
                      secretKeyRef:
                        name: backup-credentials
                        key: AWS_ACCESS_KEY_ID
                  - name: AWS_SECRET_ACCESS_KEY
                    valueFrom:
                      secretKeyRef:
                        name: backup-credentials
                        key: AWS_SECRET_ACCESS_KEY
                  - name: RESTIC_HOST
                    valueFrom:
                      secretKeyRef:
                        name: backup-credentials
                        key: RESTIC_HOST
                  - name: RESTIC_S3_PORT
                    valueFrom:
                      secretKeyRef:
                        name: backup-credentials
                        key: RESTIC_S3_PORT
                  - name: DATABASE_TYPE
                    value: ${DATABASE_TYPE}
                  - name: DATABASE_SVC
                    value: ${DATABASE_SVC}
                  - name: CHANGE_NAMESPACE
                    valueFrom:
                      secretKeyRef:
                        name: backup-credentials
                        key: CHANGE_NAMESPACE
                  - name: PROJECT_NAME
                    valueFrom:
                      secretKeyRef:
                        name: backup-credentials
                        key: PROJECT_NAME              
              restartPolicy: Never
    parameters:
      - name: JOB_NAME
        description: Name of the job. It has to be unique in the project (just add a number in the name)
        displayName: Name of the job.
        value: project-database-restore
        required: true
      - name: DATABASE_TYPE
        displayName: Type of restored database.
        description: Type of database to make restore. Values is postgresql and mysql.
        value: postgresql
        required: true
      - name: DATABASE_SVC
        displayName: Name of the service or IP address
        description: DNS name or IP address of exposed database service
        value: postgresql
        required: true
  - kind: Template
    apiVersion: v1
    metadata:
      name: restore-project-all-files
      annotations:
        description: "Template creates job to run files restore for ALL PVC in the project (using latest snapshot). 
        It will create PVCs if needed from your project metadata backup."
        tags: "restore"
    objects:
      - kind: Job
        apiVersion: batch/v1
        metadata:
          name: ${JOB_NAME}
          annotations:
            description: Restore project files for ALL PVCs
        spec:
          parallelism: 1
          completions: 1
          template:
            metadata:
              name: project-all-files-restore
            spec:
              containers:
              - name: project-all-files-restore
                image: docker.io/vadimzharov/openshift-restore-image:latest
                env:
                  - name: RESTIC_PASSWORD
                    valueFrom:
                      secretKeyRef:
                        name: backup-credentials
                        key: RESTIC_PASSWORD
                  - name: NEW_PROJECT_NAME
                    valueFrom:
                      fieldRef:
                        fieldPath: metadata.namespace  
                  - name: RESTIC_DESTINATION
                    valueFrom:
                      secretKeyRef:
                        name: backup-credentials
                        key: RESTIC_DESTINATION
                  - name: AWS_ACCESS_KEY_ID
                    valueFrom:
                      secretKeyRef:
                        name: backup-credentials
                        key: AWS_ACCESS_KEY_ID
                  - name: AWS_SECRET_ACCESS_KEY
                    valueFrom:
                      secretKeyRef:
                        name: backup-credentials
                        key: AWS_SECRET_ACCESS_KEY
                  - name: RESTIC_HOST
                    valueFrom:
                      secretKeyRef:
                        name: backup-credentials
                        key: RESTIC_HOST
                  - name: RESTIC_S3_PORT
                    valueFrom:
                      secretKeyRef:
                        name: backup-credentials
                        key: RESTIC_S3_PORT
                  - name: RESTIC_SNAPSHOT
                    value: 'latest'
                  - name: BACKUP_TYPE
                    value: all-pvc
                  - name: CHANGE_NAMESPACE
                    valueFrom:
                      secretKeyRef:
                        name: backup-credentials
                        key: CHANGE_NAMESPACE
                  - name: PROJECT_NAME
                    valueFrom:
                      secretKeyRef:
                        name: backup-credentials
                        key: PROJECT_NAME
              restartPolicy: Never
              serviceAccount: restore-sa
              serviceAccountName: restore-sa
    parameters:
      - name: JOB_NAME
        displayName: Name of the job
        description: Enter name of the job. It has to be unique in the project
        value: project-all-files-restore
        required: true
parameters:
  - name: GLOBAL_RESTIC_PASSWORD 
    displayName: Password for restic repository
    description: Password for restic repository. If repository doesn't exist - it will be initiated. 
    value: 123qweASD
    required: true
  - name: GLOBAL_RESTIC_DESTINATION
    displayName: Which type of storage you use to store your backup (aws or s3)?
    description: Destination to store backups. Set up 'aws' (AMAZON S3 storage) or 's3' (generic S3 server - like minio)
    value: s3
    required: true
  - name: GLOBAL_RESTIC_HOST
    displayName: Hostname of the server with backups
    description: "Server (s3) where you plan to store your backups. For 'aws' should be like s3.amazonaws.com/my_bucket
    for 's3' should be like mys3.mydc.com
    Finally, restic repository for 'aws' will be s3:s3.amazonaws.com/my_bucket, 
    and for 's3' will be s3:http://mys3.mydc.com:<port>/"
    value: jump02.home.msk
    required: true
  - name: GLOBAL_RESTIC_S3_PORT
    displayName: TCP port of your S3 server (will be ignored for AWS)
    description: TCP port for your S3 server (default is 9000)
    value: '9000'
  - name: GLOBAL_AWS_ACCESS_KEY_ID
    displayName: Access key for your S3 server or Amazon bucket
    description: Access key for your S3 server or Amazon bucket
    value: 123qweASD
    required: true
  - name: GLOBAL_AWS_SECRET_ACCESS_KEY
    displayName: Secret access key for your S3 server or Amazon bucket
    description: Secret access key for your S3 server or Amazon bucket
    value: 123qweASD
    required: true
  - name: GLOBAL_CHANGE_NAMESPACE
    displayName: Do you want to restore your project into project with different name?
    description: Type "yes" if you want to your current project name is different from project name which you used for backup
    value: no
  - name: GLOBAL_PROJECT_NAME
    displayName: If yes - what was name of your previous project?
    description: If you want to restore to current project from project with different name - type name of your previous project
    value: ""
labels:
  openshift-backup: templates